</$objtype/mkfile
BIN=$home/bin/$objtype/path
TARG=\
	a∗\
	bfs\
	dijkstra\

HFILES=../asif.h dat.h fns.h
OFILES=\
	../emalloc.$O\
	../dprint.$O\
	client.$O\
	drw.$O\
	fs.$O\
	grid.$O\
	map.$O\

</sys/src/cmd/mkmany

$O.dijkstra: $OFILES dijkstra.$O ../pheap.$O
$O.a∗: $OFILES a∗.$O ../pheap.$O
$O.bfs: $OFILES bfs.$O ../vec.$O

dicks:V:
	mkdir -p $BIN
install:V:	dicks
%.$O:	%.c
	$CC -o $target $CFLAGS $stem.c
CLEANFILES=`{echo ../*.[$OS]}
