</$objtype/mkfile
BIN=$home/bin/$objtype/path
TARG=\
	dijkstra\
	a∗\

HFILES=../asif.h dat.h fns.h
OFILES=\
	../emalloc.$O\
	client.$O\
	drw.$O\
	fs.$O\
	map.$O\

</sys/src/cmd/mkmany

$O.dijkstra: $OFILES dijkstra.$O ../pheap.$O
$O.a∗: $OFILES a∗.$O ../pheap.$O

dicks:V:
	mkdir -p $BIN
install:V:	dicks
%.$O:	%.c
	$CC -o $target $CFLAGS $stem.c
CLEANFILES=`{echo ../*.[$OS]}
