void	init(char*, Vertex, int, int, int);
Node*	scrselect(Point);
void	updatedrw(void);
void	evloop(void);
int	readscen(char*, Vertex*, int*, int*, int*);
void	initfs(void);
int	initmap(char*, Vertex, int, int, int);
void	initdrw(void);
void	resetdrw(void);
Vertex	n2s(Node*);
void	clearmap(void);
int	setparm(int, int, int);
